"""Initial schema

Revision ID: 04cca2b51c29
Revises: 
Create Date: 2026-01-29 06:01:15.002965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04cca2b51c29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beliefs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meditation_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('has_inner_timers', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=False),
    sa.Column('initial_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gate_exercise_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('final_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voice_note_s3_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voice_note_duration_seconds', sa.Float(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('transcription_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timer_presets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timer_presets')
    op.drop_table('prompt_settings')
    op.drop_table('prompt_responses')
    op.drop_table('meditation_sessions')
    op.drop_table('beliefs')
    # ### end Alembic commands ###
